### ISSUE TITLE
Please do not use `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by peaceiris** [touyu/memo#1]
Check your GitHub Pages status, you find that GitHub Pages build event did not start.

- Please do not use `GITHUB_TOKEN`, use `ACTIONS_DEPLOY_KEY` or `PERSONAL_TOKEN` 
  - cf. https://github.com/peaceiris/actions-gh-pages/issues/9
- Please use the latest version of peaceiris/actions-gh-pages
  - [Releases · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/releases)

**Comment by touyu** [comment]
thanks
