### ISSUE TITLE
Add RSS support

### ISSUE THREAD

**Issue by p-chan** [touyu/memo#2]

**Comment by touyu** [comment]
https://gohugo.io/templates/rss/
このあたりかな、あんまりよくわかってないけど、やってみようとおもうぞい

**Comment by touyu** [comment]
https://memo.touyu.me/index.xml
`index.xml` は、hugoが自動で作ってくれてるっぽいけど、エラー吐いてるのか

> This page contains the following errors:
> error on line 53 at column 20: PCDATA invalid Char value 8
> Below is a rendering of the page up to the first error.

**Comment by touyu** [comment]
@p-chan 多分↑のPRで対応できたんじゃないだろうか

**Comment by p-chan** [comment]
@touyu thanks!!
